### ISSUE TITLE
data/ngc.csv is missing

### ISSUE THREAD

**Issue by JohnHBrock** [potzie/starchart#1]
When I try running "chart.py -r 4 -d 50 -f 60 --out output", I get an error that data/ngc.csv cannot be found.

**Comment by Fingel** [comment]
All data seems to be missing, I am curious where do find it. I found the Tycho-2 catalog but it doesn't seem to be in the same format the program is expecting. NGC I have no idea where to find. Any help appreciated.

**Comment by astro-derek** [comment]
Hi -
forgot I had this code up on github... I have another more up to date version which I will update soon.

**Comment by Fingel** [comment]
@potzie sounds great! Thanks.

**Comment by astro-derek** [comment]
updated repo... tycho2 catalog file is too big to host on github.
